#include "src/common/ostream.h"

std::ostream& operator<<(std::ostream& os, const ISTATUS& status) {
  switch (status) {
    case ISTATUS_SUCCESS:
      return os << "ISTATUS_SUCCESS";
    case ISTATUS_ALLOCATION_FAILED:
      return os << "ISTATUS_ALLOCATION_FAILED";
    case ISTATUS_ARITHMETIC_ERROR:
      return os << "ISTATUS_ARITHMETIC_ERROR";
    case ISTATUS_INTEGER_OVERFLOW:
      return os << "ISTATUS_INTEGER_OVERFLOW";
    case ISTATUS_IO_ERROR:
      return os << "ISTATUS_IO_ERROR";
    case ISTATUS_NO_INTERSECTION:
      return os << "ISTATUS_NO_INTERSECTION";
    case ISTATUS_INVALID_ARGUMENT_00:
      return os << "ISTATUS_INVALID_ARGUMENT_00";
    case ISTATUS_INVALID_ARGUMENT_01:
      return os << "ISTATUS_INVALID_ARGUMENT_01";
    case ISTATUS_INVALID_ARGUMENT_02:
      return os << "ISTATUS_INVALID_ARGUMENT_02";
    case ISTATUS_INVALID_ARGUMENT_03:
      return os << "ISTATUS_INVALID_ARGUMENT_03";
    case ISTATUS_INVALID_ARGUMENT_04:
      return os << "ISTATUS_INVALID_ARGUMENT_04";
    case ISTATUS_INVALID_ARGUMENT_05:
      return os << "ISTATUS_INVALID_ARGUMENT_05";
    case ISTATUS_INVALID_ARGUMENT_06:
      return os << "ISTATUS_INVALID_ARGUMENT_06";
    case ISTATUS_INVALID_ARGUMENT_07:
      return os << "ISTATUS_INVALID_ARGUMENT_07";
    case ISTATUS_INVALID_ARGUMENT_08:
      return os << "ISTATUS_INVALID_ARGUMENT_08";
    case ISTATUS_INVALID_ARGUMENT_09:
      return os << "ISTATUS_INVALID_ARGUMENT_09";
    case ISTATUS_INVALID_ARGUMENT_10:
      return os << "ISTATUS_INVALID_ARGUMENT_10";
    case ISTATUS_INVALID_ARGUMENT_11:
      return os << "ISTATUS_INVALID_ARGUMENT_11";
    case ISTATUS_INVALID_ARGUMENT_12:
      return os << "ISTATUS_INVALID_ARGUMENT_12";
    case ISTATUS_INVALID_ARGUMENT_13:
      return os << "ISTATUS_INVALID_ARGUMENT_13";
    case ISTATUS_INVALID_ARGUMENT_14:
      return os << "ISTATUS_INVALID_ARGUMENT_14";
    case ISTATUS_INVALID_ARGUMENT_15:
      return os << "ISTATUS_INVALID_ARGUMENT_15";
    case ISTATUS_INVALID_ARGUMENT_16:
      return os << "ISTATUS_INVALID_ARGUMENT_16";
    case ISTATUS_INVALID_ARGUMENT_17:
      return os << "ISTATUS_INVALID_ARGUMENT_17";
    case ISTATUS_INVALID_ARGUMENT_18:
      return os << "ISTATUS_INVALID_ARGUMENT_18";
    case ISTATUS_INVALID_ARGUMENT_19:
      return os << "ISTATUS_INVALID_ARGUMENT_19";
    case ISTATUS_INVALID_ARGUMENT_20:
      return os << "ISTATUS_INVALID_ARGUMENT_20";
    case ISTATUS_INVALID_ARGUMENT_21:
      return os << "ISTATUS_INVALID_ARGUMENT_21";
    case ISTATUS_INVALID_ARGUMENT_22:
      return os << "ISTATUS_INVALID_ARGUMENT_22";
    case ISTATUS_INVALID_ARGUMENT_23:
      return os << "ISTATUS_INVALID_ARGUMENT_23";
    case ISTATUS_INVALID_ARGUMENT_24:
      return os << "ISTATUS_INVALID_ARGUMENT_24";
    case ISTATUS_INVALID_ARGUMENT_25:
      return os << "ISTATUS_INVALID_ARGUMENT_25";
    case ISTATUS_INVALID_ARGUMENT_26:
      return os << "ISTATUS_INVALID_ARGUMENT_26";
    case ISTATUS_INVALID_ARGUMENT_27:
      return os << "ISTATUS_INVALID_ARGUMENT_27";
    case ISTATUS_INVALID_ARGUMENT_28:
      return os << "ISTATUS_INVALID_ARGUMENT_28";
    case ISTATUS_INVALID_ARGUMENT_29:
      return os << "ISTATUS_INVALID_ARGUMENT_29";
    case ISTATUS_INVALID_ARGUMENT_30:
      return os << "ISTATUS_INVALID_ARGUMENT_30";
    case ISTATUS_INVALID_ARGUMENT_31:
      return os << "ISTATUS_INVALID_ARGUMENT_31";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_00:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_00";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_01:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_01";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_02:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_02";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_03:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_03";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_04:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_04";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_05:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_05";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_06:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_06";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_07:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_07";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_08:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_08";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_09:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_09";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_10:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_10";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_11:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_11";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_12:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_12";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_13:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_13";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_14:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_14";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_15:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_15";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_16:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_16";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_17:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_17";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_18:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_18";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_19:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_19";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_20:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_20";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_21:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_21";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_22:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_22";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_23:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_23";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_24:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_24";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_25:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_25";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_26:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_26";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_27:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_27";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_28:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_28";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_29:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_29";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_30:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_30";
    case ISTATUS_INVALID_ARGUMENT_COMBINATION_31:
      return os << "ISTATUS_INVALID_ARGUMENT_COMBINATION_31";
    case ISTATUS_INVALID_RESULT:
      return os << "ISTATUS_INVALID_RESULT";
  }

  assert(false);

  return os << "Invalid ISTATUS";
}

std::ostream& operator<<(std::ostream& os, const POINT3& point) {
  return os << "(" << point.x << ", " << point.y << ", " << point.z << ")";
}